
import type { Contact } from '@/lib/types';

export const mockContacts: Contact[] = [
  {
    id: "1",
    ownerId: "user1",
    name: "Chandra Oli",
    photoURL: "https://picsum.photos/seed/chandra/200/200",
    category: "Friend",
    tags: ["BNKS", "Univ. of Cincinnati", "Software Engineer"],
    locationDetails: "Ohio → Univ. of Cincinnati, Mechanical Engineer",
    occupation: "Software Engineer",
    company: "Tech Innovations Inc.",
    socialProfiles: {
      linkedin: "linkedin.com/in/chandraoli",
      twitter: "twitter.com/chandraoli",
    },
    phone: "555-123-4567",
    email: "chandra.oli@example.com",
    birthday: "1995-08-15",
    notes: "Met at college. Great friend, always helpful. Enjoys hiking and coding.",
    relationships: [
      { relatedContactId: "2", type: "Friend" },
      { relatedContactId: "3", type: "Acquaintance" },
    ],
    photosTogether: [
        "https://picsum.photos/seed/chandra_event1/300/200",
        "https://picsum.photos/seed/chandra_event2/300/200"
    ],
    createdAt: new Date("2022-01-10T10:00:00Z"),
    updatedAt: new Date("2024-05-01T14:30:00Z"),
  },
  {
    id: "2",
    ownerId: "user1",
    name: "Ritisha KC",
    photoURL: "https://picsum.photos/seed/ritisha/200/200",
    category: "Partner",
    tags: ["Nursing Student", "Cincinnati", "Healthcare"],
    locationDetails: "Cincinnati, OH",
    occupation: "Nursing Student",
    company: "University Hospital",
     socialProfiles: {
      instagram: "instagram.com/ritishakc",
    },
    email: "ritisha.kc@example.com",
    birthday: "1996-04-22",
    notes: "Supportive partner. Loves to travel and try new foods.",
    relationships: [{ relatedContactId: "1", type: "Partner" }],
    photosTogether: ["https://picsum.photos/seed/ritisha_trip/300/200"],
    createdAt: new Date("2021-06-15T10:00:00Z"),
    updatedAt: new Date("2024-07-12T11:00:00Z"),
  },
  {
    id: "3",
    ownerId: "user1",
    name: "Abhas Oli",
    photoURL: "https://picsum.photos/seed/abhas/200/200",
    category: "Friend",
    tags: ["Beloit College", "Computer Science", "Gaming"],
    locationDetails: "Wisconsin → Beloit College, Computer Science",
    occupation: "Student",
    company: "Beloit College",
    email: "abhas.oli@example.com",
    birthday: "2002-11-05",
    notes: "Younger brother's friend. Very bright and into competitive gaming.",
    relationships: [],
    photosTogether: [],
    createdAt: new Date("2023-03-20T10:00:00Z"),
    updatedAt: new Date("2024-06-25T09:15:00Z"),
  },
  {
    id: "4",
    ownerId: "user1",
    name: "Sam Hendrickson",
    photoURL: "https://picsum.photos/seed/sam/200/200",
    category: "Colleague",
    tags: ["Gustavus Adolphus", "Biology", "Research"],
    locationDetails: "Minnesota, Biology Major",
    occupation: "Research Assistant",
    company: "Mayo Clinic",
     socialProfiles: {
      linkedin: "linkedin.com/in/samhendrickson",
    },
    email: "sam.hendrickson@example.com",
    notes: "Former colleague from a summer internship. Passionate about genetics.",
    relationships: [],
    photosTogether: [],
    createdAt: new Date("2022-09-01T10:00:00Z"),
    updatedAt: new Date("2024-03-10T16:00:00Z"),
  },
   {
    id: "5",
    ownerId: "user1",
    name: "Dr. Emily Carter",
    photoURL: "https://picsum.photos/seed/emilycarter/200/200",
    category: "Professional",
    tags: ["Mentor", "Professor", "Physics"],
    locationDetails: "Stanford University",
    occupation: "Professor of Physics",
    company: "Stanford University",
    email: "emily.carter@stanford.edu",
    notes: "PhD advisor and mentor. Incredibly supportive and knowledgeable.",
    relationships: [],
    photosTogether: [],
    createdAt: new Date("2018-08-20T10:00:00Z"),
    updatedAt: new Date("2024-02-15T12:45:00Z"),
  },
];
