
import type { Contact } from '@/lib/types';

export const mockContacts: Contact[] = [
  {
    id: "1",
    ownerId: "user1",
    name: "Chandra Oli",
    photoURL: "https://picsum.photos/seed/chandra/200/200",
    category: "Friend",
    tags: ["BNKS", "Univ. of Cincinnati", "Software Engineer"],
    locationDetails: "Ohio → Univ. of Cincinnati, Mechanical Engineer",
    occupation: "Software Engineer",
    company: "Tech Innovations Inc.",
    college: "University of Cincinnati",
    socialProfiles: {
      linkedin: "linkedin.com/in/chandraoli",
      twitter: "twitter.com/chandraoli",
    },
    phone: "555-123-4567",
    email: "chandra.oli@example.com",
    birthday: "1995-08-15",
    notes: "Met at college. Great friend, always helpful. Enjoys hiking and coding.",
    relationships: [
      { relatedContactId: "2", type: "Friend" },
      { relatedContactId: "3", type: "Acquaintance" },
    ],
    photosTogether: [
        "https://picsum.photos/seed/chandra_event1/300/200",
        "https://picsum.photos/seed/chandra_event2/300/200"
    ],
    createdAt: new Date("2022-01-10T10:00:00Z"),
    updatedAt: new Date("2024-05-01T14:30:00Z"),
  },
  {
    id: "2",
    ownerId: "user1",
    name: "Ritisha KC",
    photoURL: "https://picsum.photos/seed/ritisha/200/200",
    category: "Partner",
    tags: ["Nursing Student", "Cincinnati", "Healthcare"],
    locationDetails: "Cincinnati, OH",
    occupation: "Nursing Student",
    company: "University Hospital",
    college: "University of Cincinnati", // Example
     socialProfiles: {
      instagram: "instagram.com/ritishakc",
    },
    email: "ritisha.kc@example.com",
    birthday: "1996-04-22",
    notes: "Supportive partner. Loves to travel and try new foods.",
    relationships: [{ relatedContactId: "1", type: "Partner" }],
    photosTogether: ["https://picsum.photos/seed/ritisha_trip/300/200"],
    createdAt: new Date("2021-06-15T10:00:00Z"),
    updatedAt: new Date("2024-07-12T11:00:00Z"),
  },
  {
    id: "3",
    ownerId: "user1",
    name: "Abhas Oli",
    photoURL: "https://picsum.photos/seed/abhas/200/200",
    category: "Friend",
    tags: ["Beloit College", "Computer Science", "Gaming"],
    locationDetails: "Wisconsin → Beloit College, Computer Science",
    occupation: "Student",
    company: "Beloit College", // Using company for current institution if student
    college: "Beloit College",
    email: "abhas.oli@example.com",
    birthday: "2002-11-05",
    notes: "Younger brother's friend. Very bright and into competitive gaming.",
    relationships: [],
    photosTogether: [],
    createdAt: new Date("2023-03-20T10:00:00Z"),
    updatedAt: new Date("2024-06-25T09:15:00Z"),
  },
  {
    id: "4",
    ownerId: "user1",
    name: "Sam Hendrickson",
    photoURL: "https://picsum.photos/seed/sam/200/200",
    category: "Colleague",
    tags: ["Gustavus Adolphus", "Biology", "Research"],
    locationDetails: "Minnesota, Biology Major",
    occupation: "Research Assistant",
    company: "Mayo Clinic",
    college: "Gustavus Adolphus College",
     socialProfiles: {
      linkedin: "linkedin.com/in/samhendrickson",
    },
    email: "sam.hendrickson@example.com",
    notes: "Former colleague from a summer internship. Passionate about genetics.",
    relationships: [
        { relatedContactId: "emily_g", type: "Partner", customLabel: "Partner (Emily Grenecer)" },
        { relatedContactId: "alpine_d", type: "Pet", customLabel: "Alpine (Dog)" },
        { relatedContactId: "shula_d", type: "Pet", customLabel: "Shula (Dog)" },
        { relatedContactId: "sara_h", type: "Parent", customLabel: "Sara Hendrickson (Mother)"},
        { relatedContactId: "john_h", type: "Parent", customLabel: "John Hendrickson (Father)"},
        { relatedContactId: "greta_h", type: "Sibling", customLabel: "Greta Hendrickson (Sister)"},
        { relatedContactId: "philip_e", type: "Uncle", customLabel: "Philip Eidsvold (Uncle)"},
        { relatedContactId: "ty_b", type: "Uncle", customLabel: "Ty Baucum (Uncle)"},
        { relatedContactId: "ryan_h", type: "Uncle", customLabel: "Ryan Hendrickson (Uncle)"},
        { relatedContactId: "jim_e", type: "Grandparent", customLabel: "Jim Eidsvold (Grandfather)"},
        { relatedContactId: "anne_e", type: "Grandparent", customLabel: "Anne Eidsvold (Grandmother)"},
    ],
    photosTogether: [],
    createdAt: new Date("2022-09-01T10:00:00Z"),
    updatedAt: new Date("2024-03-10T16:00:00Z"),
  },
   {
    id: "5",
    ownerId: "user1",
    name: "Dr. Emily Carter",
    photoURL: "https://picsum.photos/seed/emilycarter/200/200",
    category: "Professional",
    tags: ["Mentor", "Professor", "Physics"],
    locationDetails: "Stanford University",
    occupation: "Professor of Physics",
    company: "Stanford University",
    college: "Stanford University", // Assuming she also works where she studied, or it's her primary affiliation
    email: "emily.carter@stanford.edu",
    notes: "PhD advisor and mentor. Incredibly supportive and knowledgeable.",
    relationships: [],
    photosTogether: [],
    createdAt: new Date("2018-08-20T10:00:00Z"),
    updatedAt: new Date("2024-02-15T12:45:00Z"),
  },
  // Contacts for Sam Hendrickson's network
  { id: "emily_g", ownerId: "user1", name: "Emily Grenecer", occupation: "Peace Corps Volunteer", locationDetails: "Portland, Maine", tags: ["Partner", "Peace Corps"], createdAt: new Date(), updatedAt: new Date(), relationships: [{ relatedContactId: "4", type: "Partner" }], photosTogether: [], birthday: "1999-07-25" },
  { id: "alpine_d", ownerId: "user1", name: "Alpine (Dog)", category: "Pet", tags: ["Dog", "Black Labrador"], createdAt: new Date(), updatedAt: new Date(), relationships: [{ relatedContactId: "4", type: "Owner" }], photosTogether: [] },
  { id: "shula_d", ownerId: "user1", name: "Shula (Dog)", category: "Pet", tags: ["Dog", "Black Labrador"], createdAt: new Date(), updatedAt: new Date(), relationships: [{ relatedContactId: "4", type: "Owner" }], photosTogether: [] },
  { id: "sara_h", ownerId: "user1", name: "Sara Hendrickson", category: "Family", tags: ["Parent", "Mother"], createdAt: new Date(), updatedAt: new Date(), relationships: [{ relatedContactId: "4", type: "Child" }], photosTogether: [] },
  { id: "john_h", ownerId: "user1", name: "John Hendrickson", occupation: "DNR Engineer", locationDetails: "Duluth", category: "Family", tags: ["Parent", "Father"], createdAt: new Date(), updatedAt: new Date(), relationships: [{ relatedContactId: "4", type: "Child" }], photosTogether: [] },
  { id: "greta_h", ownerId: "user1", name: "Greta Hendrickson", occupation: "Student", locationDetails: "College in NY", category: "Family", tags: ["Sibling", "Sister", "Skiing"], college: "College in NY", createdAt: new Date(), updatedAt: new Date(), relationships: [{ relatedContactId: "4", type: "Sibling" }], photosTogether: [] },
  { id: "philip_e", ownerId: "user1", name: "Philip Eidsvold", occupation: "VP Marketing", company: "One10", locationDetails: "Edina, MN", category: "Family", tags: ["Uncle", "Marketing"], createdAt: new Date(), updatedAt: new Date(), relationships: [{ relatedContactId: "4", type: "Nephew/Niece" }], photosTogether: [] },
  { id: "ty_b", ownerId: "user1", name: "Ty Baucum", occupation: "Owner", company: "Wovenbyrd", category: "Family", tags: ["Uncle", "Business Owner"], createdAt: new Date(), updatedAt: new Date(), relationships: [{ relatedContactId: "4", type: "Nephew/Niece" }], photosTogether: [] },
  { id: "ryan_h", ownerId: "user1", name: "Ryan Hendrickson", category: "Family", tags: ["Uncle"], createdAt: new Date(), updatedAt: new Date(), relationships: [{ relatedContactId: "4", type: "Nephew/Niece" }], photosTogether: [] },
  { id: "jim_e", ownerId: "user1", name: "Jim Eidsvold", category: "Family", tags: ["Grandparent", "Grandfather"], createdAt: new Date(), updatedAt: new Date(), relationships: [{ relatedContactId: "4", type: "Grandchild" }], photosTogether: [] },
  { id: "anne_e", ownerId: "user1", name: "Anne Eidsvold", category: "Family", tags: ["Grandparent", "Grandmother"], createdAt: new Date(), updatedAt: new Date(), relationships: [{ relatedContactId: "4", type: "Grandchild" }], photosTogether: [] },
];
